import * as THREE from "three";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { FBXLoader } from "three/addons/loaders/FBXLoader.js";

export type CharacterCapabilities = {
  loaded: boolean; hasRig: boolean; hasAnimations: boolean; hasFacialMorphs: boolean; animationCount: number; boneMap: Record<string, boolean>;
};

export class AdamScene {
  renderer: THREE.WebGLRenderer; camera: THREE.OrthographicCamera; scene = new THREE.Scene(); clock = new THREE.Clock(); root = new THREE.Group();
  private loader = new GLTFLoader(); private objectUrls: string[] = []; private quality: "auto"|"low"|"medium"|"high" = "auto"; private contextLost=false;
  private mixer?: THREE.AnimationMixer; private actions: THREE.AnimationAction[]=[]; private activeAction?: THREE.AnimationAction; private model?: THREE.Object3D;
  private bones=new Map<string,THREE.Object3D>(); private baseRotations=new Map<THREE.Object3D,THREE.Euler>(); private morphTargets:Array<{mesh:THREE.Mesh;index:number}>=[];
  private talking=false; private blinkTargets:Array<{mesh:THREE.Mesh;index:number}>=[]; private blinkTime=2.5; private blinkActive=false;
  private emotion:"neutral"|"happy"|"thinking"|"confused"|"surprised"|"listening"|"speaking"="neutral"; private gestureQueue:string[]=[]; private talkTime=0; private idleTime=0; private idleClipIndex=-1;
  private state:"idle"|"walk"|"run"|"gesture"="idle"; private stateIndex=new Map<string,number>(); private boneAliases=new Map<string,THREE.Object3D>();
  private capabilities:CharacterCapabilities={loaded:false,hasRig:false,hasAnimations:false,hasFacialMorphs:false,animationCount:0,boneMap:{}};
  constructor(canvas:HTMLCanvasElement){this.renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,preserveDrawingBuffer:false,powerPreference:"high-performance"});this.renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.renderer.domElement.addEventListener("webglcontextlost",e=>{e.preventDefault();this.contextLost=true});this.renderer.domElement.addEventListener("webglcontextrestored",()=>{this.contextLost=false;this.renderer.setClearColor(0,0);this.resize()});this.renderer.setClearColor(0,0);this.camera=new THREE.OrthographicCamera(-1,1,1,-1,.1,100);this.camera.position.set(0,0,8);this.scene.add(new THREE.HemisphereLight(0xffffff,0x445066,2));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(2,4,6);this.scene.add(key);this.scene.add(this.root);this.resize();this.animate()}
  getCapabilities(){return {...this.capabilities,boneMap:{...this.capabilities.boneMap}}} getRenderStatus(){return{contextLost:this.contextLost,quality:this.quality,pixelRatio:this.renderer.getPixelRatio(),webgl2:!!this.renderer.capabilities?.isWebGL2}}
  setQuality(q:"auto"|"low"|"medium"|"high"){this.quality=q;const d=window.devicePixelRatio||1;const r=q==="low"?1:q==="medium"?Math.min(d,1.5):q==="high"?Math.min(d,2.5):Math.min(d,2);this.renderer.setPixelRatio(r);this.resize()}
  private resetState(){this.root.clear();this.mixer?.stopAllAction();this.mixer=undefined;this.actions=[];this.activeAction=undefined;this.model=undefined;this.bones.clear();this.boneAliases.clear();this.stateIndex.clear();this.baseRotations.clear();this.morphTargets=[];this.blinkTargets=[];this.blinkTime=2.5;this.blinkActive=false;this.gestureQueue=[];this.talking=false;this.talkTime=0;this.idleTime=0;this.idleClipIndex=-1;this.state="idle";this.capabilities={loaded:false,hasRig:false,hasAnimations:false,hasFacialMorphs:false,animationCount:0,boneMap:{}}}
  async load(url:string):Promise<CharacterCapabilities>{this.resetState();try{const gltf=await this.loader.loadAsync(url);this.installModel(gltf.scene,gltf.animations)}catch{this.createFallback()}return this.getCapabilities()}
  async loadFiles(files:File[]):Promise<CharacterCapabilities>{const valid=files.filter(f=>/\.(glb|gltf|fbx|bin|png|jpg|jpeg|webp|ktx2)$/i.test(f.name));const main=valid.find(f=>/\.(glb|gltf|fbx)$/i.test(f.name));if(!main)throw new Error("Select a GLB, GLTF, or FBX character model.");if(main.size>200*1024*1024)throw new Error("Character file is larger than 200MB.");this.objectUrls.forEach(URL.revokeObjectURL);this.objectUrls=[];const map=new Map<string,string>();for(const file of valid){const u=URL.createObjectURL(file);this.objectUrls.push(u);map.set(file.name.toLowerCase(),u)}const manager=new THREE.LoadingManager();manager.setURLModifier(requested=>{const clean=decodeURIComponent(requested).split(/[?#]/)[0].replace(/\\/g,"/");const base=clean.substring(clean.lastIndexOf("/")+1).toLowerCase();return map.get(clean.toLowerCase())??map.get(base)??requested});const url=map.get(main.name.toLowerCase());if(!url)throw new Error("Unable to create a local model URL.");this.resetState();if(/\.fbx$/i.test(main.name)){const object=await new FBXLoader(manager).loadAsync(url);this.installModel(object,object.animations);return this.getCapabilities()}const gltf=await new GLTFLoader(manager).loadAsync(url);this.installModel(gltf.scene,gltf.animations);return this.getCapabilities()}
  private installModel(object:THREE.Object3D,animations:THREE.AnimationClip[]){this.model=object;this.root.add(object);this.indexBones(object);this.indexMouthMorphs(object);this.fit(object);this.capabilities={loaded:true,hasRig:this.bones.size>0,hasAnimations:animations.length>0,hasFacialMorphs:this.morphTargets.length>0,animationCount:animations.length,boneMap:{}};animations.forEach((clip,i)=>{const n=clip.name.toLowerCase();if(!this.stateIndex.has("idle")&&/idle|breath|stand|rest/.test(n))this.stateIndex.set("idle",i);if(!this.stateIndex.has("walk")&&/walk|walking|locomotion/.test(n))this.stateIndex.set("walk",i);if(!this.stateIndex.has("run")&&/run|jog|sprint/.test(n))this.stateIndex.set("run",i);if(!this.stateIndex.has("gesture")&&/wave|gesture|greet|point|clap/.test(n))this.stateIndex.set("gesture",i)});for(const key of ["head","neck","spine","leftArm","rightArm","leftForeArm","rightForeArm","leftHand","rightHand","leftUpLeg","rightUpLeg","leftLeg","rightLeg","leftFoot","rightFoot","leftEye","rightEye"])this.capabilities.boneMap[key]=!!this.boneAliases.get(key);if(animations.length){this.mixer=new THREE.AnimationMixer(object);this.actions=animations.map(c=>this.mixer!.clipAction(c));this.idleClipIndex=this.actions.findIndex(a=>/idle|breath|stand|rest/i.test(a.getClip().name));if(this.idleClipIndex>=0)this.playAnimation(this.idleClipIndex)}}
  private indexBones(obj:THREE.Object3D){obj.traverse(child=>{if(!child.name)return;const n=child.name.toLowerCase().replace(/mixamorig[:_]?/g,"").replace(/[^a-z0-9]/g,"");this.bones.set(n,child);if(child instanceof THREE.Bone)this.baseRotations.set(child,child.rotation.clone())});const a:Record<string,string[]>={head:["head"],neck:["neck"],spine:["spine","spine1","spine2"],leftArm:["leftarm","leftupperarm"],rightArm:["rightarm","rightupperarm"],leftForeArm:["leftforearm","leftlowerarm"],rightForeArm:["rightforearm","rightlowerarm"],leftHand:["lefthand"],rightHand:["righthand"],leftUpLeg:["leftupleg","leftthigh"],rightUpLeg:["rightupleg","rightthigh"],leftLeg:["leftleg","leftlowerleg"],rightLeg:["rightleg","rightlowerleg"],leftFoot:["leftfoot"],rightFoot:["rightfoot"],leftEye:["lefteye"],rightEye:["righteye"]};for(const[k,names]of Object.entries(a))for(const n of names){const b=this.bones.get(n);if(b){this.boneAliases.set(k,b);break}}}
  listAnimations(){return this.actions.map(a=>a.getClip().name)} getAnimationState(){return this.state} setState(s:"idle"|"walk"|"run"|"gesture"){this.state=s;const i=this.stateIndex.get(s);if(i!==undefined)this.playAnimation(i);else{this.activeAction?.fadeOut(.2);this.activeAction=undefined;if(s==="idle"&&this.idleClipIndex>=0)this.playAnimation(this.idleClipIndex);this.idleTime=0}}
  setTalking(v:boolean){this.talking=v;this.emotion=v?"speaking":"neutral"} setEmotion(e:"neutral"|"happy"|"thinking"|"confused"|"surprised"|"listening"|"speaking"){this.emotion=e} getEmotion(){return this.emotion} queueGesture(n:string){if(n.trim())this.gestureQueue.push(n.trim())}
  lookAtScreenPoint(x:number,y:number,w:number,h:number){const head=this.findBone("head");if(!head||w<=0||h<=0)return;const nx=THREE.MathUtils.clamp(x/w*2-1,-1,1),ny=THREE.MathUtils.clamp(y/h*2-1,-1,1),yaw=THREE.MathUtils.degToRad(15),pitch=THREE.MathUtils.degToRad(10),base=this.baseRotations.get(head);if(!base)return;head.rotation.y=THREE.MathUtils.lerp(head.rotation.y,base.y+nx*yaw,.18);head.rotation.x=THREE.MathUtils.lerp(head.rotation.x,base.x-ny*pitch,.18);for(const k of ["leftEye","rightEye"]){const eye=this.findBone(k),b=eye?this.baseRotations.get(eye):undefined;if(eye&&b){eye.rotation.y=THREE.MathUtils.lerp(eye.rotation.y,b.y+nx*THREE.MathUtils.degToRad(8),.25);eye.rotation.x=THREE.MathUtils.lerp(eye.rotation.x,b.x-ny*THREE.MathUtils.degToRad(6),.25)}}}
  private indexMouthMorphs(obj:THREE.Object3D){obj.traverse(child=>{const mesh=child as THREE.Mesh;if(!(mesh instanceof THREE.Mesh)||!mesh.morphTargetDictionary||!mesh.morphTargetInfluences)return;for(const[name,index]of Object.entries(mesh.morphTargetDictionary)){if(/blink|eyeclose|eyelid|closeeye/i.test(name))this.blinkTargets.push({mesh,index});if(/viseme|mouth|jaw|open|aa|ah|speech|talk/i.test(name))this.morphTargets.push({mesh,index})}})}
  private applyBlink(dt:number){if(!this.blinkTargets.length)return;this.blinkTime-=dt;if(this.blinkTime<=0){this.blinkActive=true;this.blinkTime=.12}else if(this.blinkActive){this.blinkActive=false;this.blinkTime=2.5+Math.random()*4}const amount=this.blinkActive?1:0;for(const t of this.blinkTargets)if(t.mesh.morphTargetInfluences)t.mesh.morphTargetInfluences[t.index]=THREE.MathUtils.lerp(t.mesh.morphTargetInfluences[t.index]||0,amount,Math.min(1,dt*20))}
  private applyTalking(dt:number){if(!this.morphTargets.length)return;this.talkTime+=dt;const amount=this.talking?.18+Math.max(0,Math.sin(this.talkTime*17))*.5:0;for(const t of this.morphTargets)if(t.mesh.morphTargetInfluences)t.mesh.morphTargetInfluences[t.index]=THREE.MathUtils.lerp(t.mesh.morphTargetInfluences[t.index]||0,amount,Math.min(1,dt*12))}
  playAnimation(i:number){if(!this.actions.length)return;const next=this.actions[Math.max(0,Math.min(i,this.actions.length-1))];if(this.activeAction===next)return;this.activeAction?.fadeOut(.25);next.reset().setEffectiveWeight(1).setEffectiveTimeScale(1).fadeIn(.25);if(this.state==="gesture")next.setLoop(THREE.LoopOnce,1).clampWhenFinished=true;next.play();this.activeAction=next;this.idleTime=0}
  playAnimationByName(n:string){const i=this.actions.findIndex(a=>a.getClip().name.toLowerCase().includes(n.toLowerCase()));if(i>=0)this.playAnimation(i)} pauseAnimation(){if(this.activeAction)this.activeAction.paused=true} resumeAnimation(){if(this.activeAction)this.activeAction.paused=false} stopAnimation(){this.activeAction?.fadeOut(.2);this.activeAction=undefined;this.idleClipIndex=-1}
  private findBone(...names:string[]){for(const n of names){const f=this.boneAliases.get(n)??this.bones.get(n.toLowerCase().replace(/[^a-z0-9]/g,""));if(f)return f}return undefined}
  private applyProceduralIdle(dt:number){if((this.activeAction&&this.stateIndex.has(this.state))||!this.model||!this.capabilities.hasRig)return;this.idleTime+=dt;const t=this.idleTime;const set=(b:THREE.Object3D|undefined,axis:"x"|"y"|"z",v:number)=>{if(!b)return;const base=this.baseRotations.get(b);if(base)b.rotation[axis]=base[axis]+v};const spine=this.findBone("spine"),head=this.findBone("head"),neck=this.findBone("neck"),la=this.findBone("leftArm"),ra=this.findBone("rightArm"),ll=this.findBone("leftLeg"),rl=this.findBone("rightLeg"),lf=this.findBone("leftFoot"),rf=this.findBone("rightFoot");set(spine,"x",Math.sin(t*1.7)*.018);set(neck,"z",Math.sin(t*.65)*.006);set(head,"y",Math.sin(t*.48)*.018);set(head,"x",Math.sin(t*.82+1.1)*.012);set(la,"z",Math.sin(t*1.1)*.008);set(ra,"z",-Math.sin(t*1.1)*.008);const step=Math.sin(t*1.35)*.006;set(ll,"x",step);set(rl,"x",-step);set(lf,"x",-step*.5);set(rf,"x",step*.5);if(this.state==="walk"||this.state==="run"){const speed=this.state==="run"?2.8:1.8,stride=Math.sin(t*speed)*(this.state==="run"?.28:.16);set(ll,"x",stride);set(rl,"x",-stride);set(la,"x",-stride*.35);set(ra,"x",stride*.35)}}
  private createFallback(){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,1,6,16),new THREE.MeshStandardMaterial({color:0x4f7cff})),head=new THREE.Mesh(new THREE.SphereGeometry(.43,24,16),new THREE.MeshStandardMaterial({color:0xffd2b3}));head.position.y=.95;const eyeMat=new THREE.MeshBasicMaterial({color:0x172033});for(const x of[-.15,.15]){const eye=new THREE.Mesh(new THREE.SphereGeometry(.045,12,8),eyeMat);eye.position.set(x,.98,.4);g.add(eye)}g.add(body,head);this.root.add(g);this.model=g;this.fit(g);this.capabilities={loaded:true,hasRig:false,hasAnimations:false,hasFacialMorphs:false,animationCount:0,boneMap:{}}}
  private fit(obj:THREE.Object3D){obj.updateWorldMatrix(true,true);const box=new THREE.Box3().setFromObject(obj),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());obj.position.sub(center);obj.scale.setScalar(1.7/Math.max(size.x,size.y,size.z,.01))}
  dispose(){this.objectUrls.forEach(URL.revokeObjectURL);this.objectUrls=[];this.root.clear();this.renderer.dispose()}
  resize(){const w=this.renderer.domElement.clientWidth||360,h=this.renderer.domElement.clientHeight||520,a=w/h;this.camera.left=-a;this.camera.right=a;this.camera.top=1;this.camera.bottom=-1;this.camera.updateProjectionMatrix();this.renderer.setSize(Math.max(1,w),Math.max(1,h),false)}
  private animate=()=>{requestAnimationFrame(this.animate);const dt=Math.min(this.clock.getDelta(),.05);this.mixer?.update(dt);this.applyProceduralIdle(dt);this.applyTalking(dt);this.applyBlink(dt);if(this.state==="gesture"&&this.activeAction&&!this.activeAction.isRunning()){this.activeAction=undefined;this.state="idle";if(this.idleClipIndex>=0)this.playAnimation(this.idleClipIndex)}if(this.gestureQueue.length&&(!this.activeAction||this.state==="idle")){const g=this.gestureQueue.shift();if(g){this.state="gesture";this.playAnimationByName(g)}}if(!this.contextLost)this.renderer.render(this.scene,this.camera)}
}
