import * as THREE from "three";
import { GLTFLoader } from "three/addons/loaders/GLTFLoader.js";
import { FBXLoader } from "three/addons/loaders/FBXLoader.js";

export type CharacterCapabilities={loaded:boolean;hasRig:boolean;hasAnimations:boolean;hasFacialMorphs:boolean;animationCount:number;boneMap:Record<string,boolean>};
type Emotion="neutral"|"happy"|"thinking"|"confused"|"surprised"|"listening"|"speaking";

export class AdamScene {
 renderer:THREE.WebGLRenderer; camera:THREE.OrthographicCamera; scene=new THREE.Scene(); clock=new THREE.Clock(); root=new THREE.Group();
 private urls:string[]=[]; private quality:"auto"|"low"|"medium"|"high"="auto"; private contextLost=false; private mixer?:THREE.AnimationMixer; private actions:THREE.AnimationAction[]=[]; private active?:THREE.AnimationAction; private model?:THREE.Object3D;
 private bones=new Map<string,THREE.Object3D>(); private bases=new Map<THREE.Object3D,THREE.Euler>(); private aliases=new Map<string,THREE.Object3D>(); private morphs:Array<{mesh:THREE.Mesh;index:number;name:string}>=[]; private blinks:Array<{mesh:THREE.Mesh;index:number}>=[]; private emotion:Emotion="neutral"; private talking=false; private talkTime=0; private blinkTimer=2.5; private blinkValue=0; private gestures:string[]=[]; private state:"idle"|"walk"|"run"|"gesture"="idle"; private stateIndex=new Map<string,number>(); private idleIndex=-1; private locomotion=0; private idleTime=0;
 private caps:CharacterCapabilities={loaded:false,hasRig:false,hasAnimations:false,hasFacialMorphs:false,animationCount:0,boneMap:{}};
 constructor(canvas:HTMLCanvasElement){this.renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,preserveDrawingBuffer:false,powerPreference:"high-performance"});this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));this.renderer.setClearColor(0,0);this.camera=new THREE.OrthographicCamera(-1,1,1,-1,.1,100);this.camera.position.z=8;this.scene.add(new THREE.HemisphereLight(0xffffff,0x445066,2));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(2,4,6);this.scene.add(key);this.scene.add(this.root);this.renderer.domElement.addEventListener("webglcontextlost",e=>{e.preventDefault();this.contextLost=true});this.renderer.domElement.addEventListener("webglcontextrestored",()=>{this.contextLost=false;this.resize()});this.resize();this.animate()}
 getCapabilities(){return {...this.caps,boneMap:{...this.caps.boneMap}}} getRenderStatus(){return{contextLost:this.contextLost,quality:this.quality,pixelRatio:this.renderer.getPixelRatio(),webgl2:this.renderer.capabilities.isWebGL2}}
 setQuality(q:"auto"|"low"|"medium"|"high"){this.quality=q;const d=devicePixelRatio||1;this.renderer.setPixelRatio(q==="low"?1:q==="medium"?Math.min(d,1.5):q==="high"?Math.min(d,2.5):Math.min(d,2));this.resize()}
 private reset(){this.root.clear();this.mixer?.stopAllAction();this.mixer=undefined;this.actions=[];this.active=undefined;this.model=undefined;this.bones.clear();this.aliases.clear();this.bases.clear();this.morphs=[];this.blinks=[];this.stateIndex.clear();this.gestures=[];this.emotion="neutral";this.talking=false;this.talkTime=0;this.blinkTimer=2.5;this.blinkValue=0;this.state="idle";this.idleIndex=-1;this.idleTime=0;this.locomotion=0;this.caps={loaded:false,hasRig:false,hasAnimations:false,hasFacialMorphs:false,animationCount:0,boneMap:{}}}
 async load(url:string){this.reset();try{const g=await new GLTFLoader().loadAsync(url);this.install(g.scene,g.animations)}catch{this.fallback()}return this.getCapabilities()}
 async loadFiles(files:File[]){const valid=files.filter(f=>/\.(glb|gltf|fbx|bin|png|jpe?g|webp|ktx2)$/i.test(f.name));const main=valid.find(f=>/\.(glb|gltf|fbx)$/i.test(f.name));if(!main)throw new Error("Select a GLB, GLTF, or FBX character model.");if(main.size>200*1024*1024)throw new Error("Character file is larger than 200MB.");this.urls.forEach(URL.revokeObjectURL);this.urls=[];const map=new Map<string,string>();for(const f of valid){const u=URL.createObjectURL(f);this.urls.push(u);map.set(f.name.toLowerCase(),u)}const manager=new THREE.LoadingManager();manager.setURLModifier(req=>{const p=decodeURIComponent(req).split(/[?#]/)[0].replace(/\\/g,"/");const b=p.substring(p.lastIndexOf("/")+1).toLowerCase();return map.get(p.toLowerCase())??map.get(b)??req});const url=map.get(main.name.toLowerCase())!;this.reset();if(/\.fbx$/i.test(main.name)){const o=await new FBXLoader(manager).loadAsync(url);this.install(o,o.animations)}else{const g=await new GLTFLoader(manager).loadAsync(url);this.install(g.scene,g.animations)}return this.getCapabilities()}
 private install(object:THREE.Object3D,clips:THREE.AnimationClip[]){this.model=object;this.root.add(object);this.indexBones(object);this.indexMorphs(object);this.fit(object);this.caps={loaded:true,hasRig:this.bones.size>0,hasAnimations:clips.length>0,hasFacialMorphs:this.morphs.length>0,animationCount:clips.length,boneMap:{}};const names:Record<string,string[]>={head:["head"],neck:["neck"],spine:["spine","spine1","spine2"],leftArm:["leftarm","leftupperarm"],rightArm:["rightarm","rightupperarm"],leftForeArm:["leftforearm","leftlowerarm"],rightForeArm:["rightforearm","rightlowerarm"],leftHand:["lefthand"],rightHand:["righthand"],leftUpLeg:["leftupleg","leftthigh"],rightUpLeg:["rightupleg","rightthigh"],leftLeg:["leftleg","leftlowerleg"],rightLeg:["rightleg","rightlowerleg"],leftFoot:["leftfoot"],rightFoot:["rightfoot"],leftEye:["lefteye"],rightEye:["righteye"]};for(const k of Object.keys(names))this.caps.boneMap[k]=this.aliases.has(k);clips.forEach((c,i)=>{const n=c.name.toLowerCase();if(!this.stateIndex.has("idle")&&/idle|breath|stand|rest/.test(n))this.stateIndex.set("idle",i);if(!this.stateIndex.has("walk")&&/walk|walking|locomotion/.test(n))this.stateIndex.set("walk",i);if(!this.stateIndex.has("run")&&/run|jog|sprint/.test(n))this.stateIndex.set("run",i);if(!this.stateIndex.has("gesture")&&/wave|gesture|greet|point|clap|nod|thumb/.test(n))this.stateIndex.set("gesture",i)});if(clips.length){this.mixer=new THREE.AnimationMixer(object);this.actions=clips.map(c=>this.mixer!.clipAction(c));this.idleIndex=this.actions.findIndex(a=>/idle|breath|stand|rest/i.test(a.getClip().name));if(this.idleIndex>=0)this.play(this.idleIndex)}}
 private indexBones(obj:THREE.Object3D){obj.traverse(o=>{if(!o.name)return;const n=o.name.toLowerCase().replace(/mixamorig[:_]?/g,"").replace(/[^a-z0-9]/g,"");this.bones.set(n,o);if(o instanceof THREE.Bone)this.bases.set(o,o.rotation.clone())});const aliases:Record<string,string[]>= {head:["head"],neck:["neck"],spine:["spine","spine1","spine2"],leftArm:["leftarm","leftupperarm"],rightArm:["rightarm","rightupperarm"],leftForeArm:["leftforearm","leftlowerarm"],rightForeArm:["rightforearm","rightlowerarm"],leftHand:["lefthand"],rightHand:["righthand"],leftUpLeg:["leftupleg","leftthigh"],rightUpLeg:["rightupleg","rightthigh"],leftLeg:["leftleg","leftlowerleg"],rightLeg:["rightleg","rightlowerleg"],leftFoot:["leftfoot"],rightFoot:["rightfoot"],leftEye:["lefteye"],rightEye:["righteye"]};for(const[k,ns]of Object.entries(aliases))for(const n of ns){const b=this.bones.get(n);if(b){this.aliases.set(k,b);break}}}
 private indexMorphs(obj:THREE.Object3D){obj.traverse(o=>{const m=o as THREE.Mesh;if(!(m instanceof THREE.Mesh)||!m.morphTargetDictionary||!m.morphTargetInfluences)return;for(const[n,i]of Object.entries(m.morphTargetDictionary)){const l=n.toLowerCase();if(/blink|eyeclose|eyelid|closeeye/.test(l))this.blinks.push({mesh:m,index:i});if(/viseme|mouth|jaw|open|aa|ah|speech|talk|smile|happy|joy|frown|sad|confus|surpris|think|brow/.test(l))this.morphs.push({mesh:m,index:i,name:l})}})}
 setEmotion(e:Emotion){this.emotion=e}
 getEmotion(){return this.emotion}
 setTalking(v:boolean){this.talking=v;if(v)this.emotion="speaking";else if(this.emotion==="speaking")this.emotion="neutral"}
 queueGesture(n:string){if(n.trim())this.gestures.push(n.trim().toLowerCase())}
 getAnimationState(){return this.state} getLocomotionDistance(){return this.locomotion}
 setState(s:"idle"|"walk"|"run"|"gesture"){this.state=s;const i=this.stateIndex.get(s);if(i!==undefined)this.play(i);else if(s==="idle"&&this.idleIndex>=0)this.play(this.idleIndex);this.idleTime=0}
 listAnimations(){return this.actions.map(a=>a.getClip().name)}
 playAnimationByName(n:string){const i=this.actions.findIndex(a=>a.getClip().name.toLowerCase().includes(n.toLowerCase()));if(i>=0)this.play(i)}
 private play(i:number){if(!this.actions.length)return;const next=this.actions[Math.max(0,Math.min(i,this.actions.length-1))];if(this.active===next)return;this.active?.fadeOut(.22);next.reset().setEffectiveWeight(1).setEffectiveTimeScale(1).fadeIn(.22);if(this.state==="gesture")next.setLoop(THREE.LoopOnce,1).clampWhenFinished=true;next.play();this.active=next}
 lookAtScreenPoint(x:number,y:number,w:number,h:number){const head=this.aliases.get("head");if(!head||w<=0||h<=0)return;const nx=THREE.MathUtils.clamp(x/w*2-1,-1,1),ny=THREE.MathUtils.clamp(y/h*2-1,-1,1);const set=(k:string,a:"x"|"y",v:number)=>{const b=this.aliases.get(k),base=b?this.bases.get(b):undefined;if(b&&base)b.rotation[a]=THREE.MathUtils.lerp(b.rotation[a],base[a]+v,.2)};set("head","y",THREE.MathUtils.degToRad(nx*15));set("head","x",THREE.MathUtils.degToRad(-ny*10));set("leftEye","y",THREE.MathUtils.degToRad(nx*15));set("rightEye","y",THREE.MathUtils.degToRad(nx*15));set("leftEye","x",THREE.MathUtils.degToRad(-ny*10));set("rightEye","x",THREE.MathUtils.degToRad(-ny*10))}
 private applyEmotion(dt:number){const wanted=(e:Emotion)=>e==="happy"?/smile|happy|joy/:e==="surprised"?/surpris|wide|oh/:e==="confused"?/confus|frown|sad/:e==="thinking"?/think|brow/:e==="speaking"?/mouth|jaw|open|speech|talk|viseme/:/$a/;for(const m of this.morphs){const target=wanted(this.emotion).test(m.name)?(this.emotion==="speaking"?0.15:0.35):0;if(m.mesh.morphTargetInfluences)m.mesh.morphTargetInfluences[m.index]=THREE.MathUtils.lerp(m.mesh.morphTargetInfluences[m.index]||0,target,Math.min(1,dt*10))}}
 private applyBlink(dt:number){if(!this.blinks.length)return;this.blinkTimer-=dt;if(this.blinkTimer<=0){this.blinkTimer=.14;this.blinkValue=1}else if(this.blinkValue>0){this.blinkValue=Math.max(0,this.blinkValue-dt*10);if(this.blinkValue===0)this.blinkTimer=2.5+Math.random()*4}for(const b of this.blinks)if(b.mesh.morphTargetInfluences)b.mesh.morphTargetInfluences[b.index]=THREE.MathUtils.lerp(b.mesh.morphTargetInfluences[b.index]||0,this.blinkValue,Math.min(1,dt*24))}
 private applyProcedural(dt:number){if(!this.model||!this.caps.hasRig)return;this.idleTime+=dt;const t=this.idleTime;const set=(k:string,a:"x"|"y"|"z",v:number)=>{const b=this.aliases.get(k),base=b?this.bases.get(b):undefined;if(b&&base)b.rotation[a]=base[a]+v};set("spine","x",Math.sin(t*1.7)*.018);set("neck","z",Math.sin(t*.65)*.006);set("head","y",Math.sin(t*.48)*.018);set("head","x",Math.sin(t*.82)*.012);if(this.state==="walk"||this.state==="run"){const speed=this.state==="run"?4.2:2.6,amp=this.state==="run"?.55:.32,s=Math.sin(t*speed)*amp;set("leftLeg","x",s);set("rightLeg","x",-s);set("leftArm","x",-s*.35);set("rightArm","x",s*.35);this.locomotion+=Math.abs(s)*dt*(this.state==="run"?1.4:.8)}}}
 private fallback(){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,1,6,16),new THREE.MeshStandardMaterial({color:0x4f7cff}));const head=new THREE.Mesh(new THREE.SphereGeometry(.43,24,16),new THREE.MeshStandardMaterial({color:0xffd2b3}));head.position.y=.95;g.add(body,head);this.root.add(g);this.model=g;this.fit(g);this.caps={loaded:true,hasRig:false,hasAnimations:false,hasFacialMorphs:false,animationCount:0,boneMap:{}}}
 private fit(obj:THREE.Object3D){obj.updateWorldMatrix(true,true);const box=new THREE.Box3().setFromObject(obj),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3());obj.position.sub(center);obj.scale.setScalar(1.7/Math.max(size.x,size.y,size.z,.01))}
 resize(){const w=this.renderer.domElement.clientWidth||360,h=this.renderer.domElement.clientHeight||520,a=w/h;this.camera.left=-a;this.camera.right=a;this.camera.top=1;this.camera.bottom=-1;this.camera.updateProjectionMatrix();this.renderer.setSize(Math.max(1,w),Math.max(1,h),false)}
 dispose(){this.urls.forEach(URL.revokeObjectURL);this.urls=[];this.root.clear();this.renderer.dispose()}
 private animate=()=>{requestAnimationFrame(this.animate);const dt=Math.min(this.clock.getDelta(),.05);this.mixer?.update(dt);this.applyProcedural(dt);this.applyEmotion(dt);this.applyBlink(dt);if(this.state==="gesture"&&this.active&&!this.active.isRunning()){this.active=undefined;this.state="idle";if(this.idleIndex>=0)this.play(this.idleIndex)}if(this.gestures.length&&(!this.active||this.state==="idle")){const g=this.gestures.shift();if(g){this.state="gesture";this.playAnimationByName(g)}}if(!this.contextLost)this.renderer.render(this.scene,this.camera)}
}