use rusqlite::{params,Connection};use std::path::Path;
#[derive(Debug,Clone,serde::Serialize,serde::Deserialize)]
pub struct CalendarEvent{pub id:i64,pub title:String,pub start_at:String,pub end_at:Option<String>,pub all_day:bool,pub recurrence:Option<String>,pub weekdays:Option<String>,pub reminder_offsets:Option<String>,pub notes:Option<String>}
pub fn init(path:&Path)->Result<(),String>{let c=Connection::open(path).map_err(|e|e.to_string())?;c.execute_batch("CREATE TABLE IF NOT EXISTS calendar_events(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,start_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS idx_calendar_start ON calendar_events(start_at);").map_err(|e|e.to_string())}
pub fn add(path:&Path,title:&str,start:&str)->Result<i64,String>{add_full(path,title,start,None,false,None,None,None,None)}
pub fn add_full(path:&Path,title:&str,start:&str,end:Option<&str>,all:bool,rec:Option<&str>,days:Option<&str>,offs:Option<&str>,notes:Option<&str>)->Result<i64,String>{let c=Connection::open(path).map_err(|e|e.to_string())?;c.execute("INSERT INTO events(title,start_at,end_at,all_day,recurrence,weekdays,reminder_offsets,notes) VALUES(?,?,?,?,?,?,?,?)",params![title,start,end,all as i32,rec,days,offs,notes]).map_err(|e|e.to_string())?;Ok(c.last_insert_rowid())}
pub fn update_full(path:&Path,id:i64,title:&str,start:&str,end:Option<&str>,all:bool,rec:Option<&str>,days:Option<&str>,offs:Option<&str>,notes:Option<&str>)->Result<(),String>{let c=Connection::open(path).map_err(|e|e.to_string())?;c.execute("UPDATE events SET title=?,start_at=?,end_at=?,all_day=?,recurrence=?,weekdays=?,reminder_offsets=?,notes=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",params![title,start,end,all as i32,rec,days,offs,notes,id]).map_err(|e|e.to_string())?;Ok(())}
pub fn list(path:&Path)->Result<Vec<(i64,String,String)>,String>{let c=Connection::open(path).map_err(|e|e.to_string())?;let mut s=c.prepare("SELECT id,title,start_at FROM events ORDER BY start_at").map_err(|e|e.to_string())?;let r=s.query_map([],|x|Ok((x.get(0)?,x.get(1)?,x.get(2)?))).map_err(|e|e.to_string())?;r.map(|x|x.map_err(|e|e.to_string())).collect()}
pub fn between(path:&Path,start:&str,end:&str)->Result<Vec<CalendarEvent>,String>{let c=Connection::open(path).map_err(|e|e.to_string())?;let mut s=c.prepare("SELECT id,title,start_at,end_at,all_day,recurrence,weekdays,reminder_offsets,notes FROM events WHERE start_at>=? AND start_at<=? ORDER BY start_at").map_err(|e|e.to_string())?;let r=s.query_map(params![start,end],|x|Ok(CalendarEvent{id:x.get(0)?,title:x.get(1)?,start_at:x.get(2)?,end_at:x.get(3)?,all_day:x.get::<_,i32>(4)?!=0,recurrence:x.get(5)?,weekdays:x.get(6)?,reminder_offsets:x.get(7)?,notes:x.get(8)?})).map_err(|e|e.to_string())?;r.map(|x|x.map_err(|e|e.to_string())).collect()}
pub fn delete(path:&Path,id:i64)->Result<(),String>{let c=Connection::open(path).map_err(|e|e.to_string())?;c.execute("DELETE FROM events WHERE id=?",[id]).map_err(|e|e.to_string()).map(|_|())}
#[cfg(test)]mod tests{use super::*;#[test]fn recurrence_roundtrip(){let p=std::env::temp_dir().join("adam-cal-test.db");let _=std::fs::remove_file(&p);init(&p).unwrap();let id=add_full(&p,"x","2026-09-25T10:00:00",Some("2026-09-25T11:00:00"),false,Some("weekly"),Some("MO,WE"),Some("15"),Some("n")).unwrap();assert_eq!(between(&p,"2026-09-25","2026-09-26").unwrap()[0].id,id);let _=std::fs::remove_file(p);}}